CREATE TABLE properties (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    user_id BIGINT NOT NULL,

    nickname VARCHAR(100) NOT NULL,

    address_line1 VARCHAR(255) NOT NULL,

    suburb VARCHAR(100) NOT NULL,

    state VARCHAR(50) NOT NULL,

    postcode VARCHAR(10) NOT NULL,

    created_at TIMESTAMP NOT NULL,

    updated_at TIMESTAMP,

    move_in_date DATE, 

    move_out_date DATE,

    CONSTRAINT fk_property_user
        FOREIGN KEY (user_id)
        REFERENCES users(id)
        ON DELETE CASCADE
);