CREATE TABLE leases (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    property_id BIGINT NOT NULL,

    lease_start DATE NOT NULL,
    lease_end DATE NOT NULL,

    weekly_rent DECIMAL(10,2) NOT NULL,

    bond_amount DECIMAL(10,2) NOT NULL,

    payment_frequency VARCHAR(20) NOT NULL,

    inspection_frequency VARCHAR(20),

    notes TEXT,

    created_at TIMESTAMP NOT NULL,

    updated_at TIMESTAMP,

    CONSTRAINT fk_lease_property
        FOREIGN KEY(property_id)
        REFERENCES properties(id)
        ON DELETE CASCADE
)