CREATE TABLE payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lease_id BIGINT NOT NULL,
    amount DECIMAL(10,2) NOT NULL,
    due_date DATE NOT NULL,
    paid_date DATE,
    status VARCHAR(30) NOT NULL,
    payment_method VARCHAR(30),
    reference VARCHAR(100),
    notes TEXT,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,

    CONSTRAINT fk_payment_lease
        FOREIGN KEY (lease_id)
        REFERENCES leases(id)
        ON DELETE CASCADE
);