CREATE TABLE maintenances (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    property_id BIGINT NOT NULL,
    title TEXT, 
    description TEXT, 
    priority VARCHAR(30) NOT NULL,
    status VARCHAR(30) NOT NULL,
    reportedDate DATE NOT NULL,
    resolvedDate DATE
)